export const routes = [
    {
        id: 'home',
        title: '主页',
        type: 'item',
        icon: 'home',
        url: '/home',
    },
    {
        id: 'goods',
        title: '商品管理',
        type: 'collapse',
        icon: 'alert',
        children: [
            {
                id: 'list',
                title: '商品列表',
                type: 'item',
                url: '/goods/list',
            },
            {
                id: 'category',
                title: '商品分类',
                type: 'item',
                url: '/goods/category',
            },
            {
                id: 'comment',
                title: '商品评价',
                type: 'item',
                url: '/goods/comment',
            },
        ],
    },
    {
        id: 'order',
        title: '订单管理',
        type: 'collapse',
        icon: 'appstore',
        badge: {
            title: '7',
            bg: '#ff4081',
            fg: '#fff',
        },
        children: [
            {
                id: 'orderlist',
                title: '全部订单',
                type: 'item',
                url: '/order/list',
            },
            {
                id: 'delivery',
                title: '待发货',
                type: 'item',
                url: '/order/delivery',
            },
            {
                id: 'receipt',
                title: '待收货',
                type: 'item',
                url: '/order/receipt',
            },
            {
                id: 'pay',
                title: '待付款',
                type: 'item',
                url: '/order/pay',
            },
            {
                id: 'complete',
                title: '已完成',
                type: 'item',
                url: '/order/complete',
            },
            {
                id: 'cancel',
                title: 'cancel',
                type: 'item',
                url: '/order/cancel',
            },
            {
                id: 'refund',
                title: '售后管理',
                type: 'item',
                url: '/order/refund',
            },
        ],
    },
    {
        id: 'user',
        title: '用户管理',
        type: 'collapse',
        icon: 'build',
        badge: {
            title: '2',
            bg: '#ff6f00',
            fg: '#fff',
        },
        children: [
            {
                id: 'list',
                title: '用户列表',
                type: 'item',
                url: '/user/list',
            },
            {
                id: 'grade',
                title: '会员等级',
                type: 'item',
                url: '/user/grade',
            },
            {
                id: 'recharge',
                title: '充值记录',
                type: 'item',
                url: '/user/recharge',
            },
            {
                id: 'balance',
                title: '余额明细',
                type: 'item',
                url: '/user/balance',
            },
        ],
    },
    {
        id: 'market',
        title: '营销管理',
        type: 'collapse',
        icon: 'database',
        children: [
            {
                id: 'coupon',
                title: '优惠券列表',
                type: 'item',
                url: '/market/coupon',
            },
        ],
    },
    {
        id: 'setting',
        title: '设置',
        type: 'collapse',
        icon: 'eye',
        children: [
            {
                id: 'store',
                title: '商城设置',
                type: 'item',
                url: '/setting/store',
            },
            {
                id: 'trade',
                title: '交易设置',
                type: 'item',
                url: '/setting/trade',
            },
            {
                id: 'delivery',
                title: '运费模板',
                type: 'item',
                url: '/setting/delivery',
            },
            {
                id: 'express',
                title: '物流公司',
                type: 'item',
                url: '/setting/express',
            },
            {
                id: 'sms',
                title: '短信通知',
                type: 'item',
                url: '/setting/sms',
            },
            {
                id: 'tplmsg',
                title: '模板消息',
                type: 'item',
                url: '/setting/tplmsg',
            },
            {
                id: 'address',
                title: '退货地址',
                type: 'item',
                url: '/setting/address',
            },
            {
                id: 'storage',
                title: '上传设置',
                type: 'item',
                url: '/setting/storage',
            },
        ],
    },
];
