export default {
    prophet: {
        action: {
            delete: '删除',
            show: '详情',
            list: '列表',
            save: '保存',
            create: '新建',
            edit: '编辑',
            sort: '排序',
            cancel: '取消',
            undo: '撤销',
            refresh: '刷新',
            add: '添加',
            remove: '删除',
            back: '返回',
            bulk_actions: '选中%{smart_count}项',
            export: '导出',
            search: '搜索',
            update: '更新',
            about: '关于',
            close: '关闭',
            confirm: '确认',
            download: '下载',
            downloading: '下载中',
            logout: '退出',
            more: '更多',
            submit: '提交',
            copy: '复制',
            cut: '剪切',
            help: '帮助',
            hide: '隐藏',
            paste: '粘贴',
            quit: '退出',
            undo: '撤销',
            status: '状态',
        },
        boolean: {
            true: '是',
            false: '否',
        },
        page: {
            list: '%{name} 列表',
            edit: '%{name} #%{id}',
            show: '%{name} #%{id}',
            create: '新建 %{name}',
            dashboard: '概览',
            not_found: '未发现',
            loading: '加载中',
            error: '出现错误',
        },
        message: {
            yes: '是',
            no: '否',
            are_you_sure: '您确定操作?',
            about: '关于',
            not_found: '您输入了错误的URL或者错误的链接.',
            loading: '正在加载页面, 请稍候',
            invalid_form: '表单输入无效. 请检查错误提示',
            delete_title: '删除 %{name} #%{id}',
            delete_content: '您确定要删除该条目?',
            bulk_delete_title:
                '删除 %{name} |||| 删除 %{smart_count}项 %{name} ',
            bulk_delete_content:
                '您确定要删除 %{name}? |||| 您确定要删除 %{smart_count} 项?',
        },
        navigation: {
            no_results: '结果为空',
            no_more_results: '页码 %{page} 超出边界. 试试上一页.',
            page_out_of_boundaries: '页码 %{page} 超出边界',
            page_out_from_end: '已到最末页',
            page_out_from_begin: '已到最前页',
            page_range_info: '%{offsetBegin}-%{offsetEnd} / %{total}',
            page_rows_per_page: '每页行数:',
            next: '下一页',
            prev: '上一页',
        },
        auth: {
            user_menu: '设置',
            username: '用户名',
            password: '密码',
            sign_in: '登录',
            sign_in_error: '验证失败, 请重试',
            logout: '退出',
            disable: '您的账号已被禁用。',
            register: '注册',
            success: '注册成功',
        },
        notification: {
            updated: '更新成功 |||| %{smart_count} 项条目已更新',
            created: '创建成功',
            deleted: '删除成功 |||| %{smart_count} 项条目已删除',
            bad_item: '不正确的条目',
            item_doesnt_exist: '条目不存在',
            http_error: '系统异常',
            data_provider_error: 'dataProvider错误. 请检查console的详细信息.',
            canceled: '取消动作',
            logged_out: '当前会话已结束，请重新登陆',
        },
        validation: {
            required: '必填',
            minLength: '至少 %{min} 位字符',
            maxLength: '必须不多于 %{max} 个字符',
            minValue: '必须不小于 %{min}',
            maxValue: '必须不大于 %{max}',
            number: '必须为数字',
            email: '请输入正确的邮箱地址',
            oneOf: '必须为: %{options}其中一项',
            regex: '必须符合指定的格式 (regexp): %{pattern}',
            password: '请输入您的密码',
            confirmPassword: '确认密码',
            mobile: '请输入正确的手机号',
        },
    },
};
